// Generated from `src/lib/schema.contract.json` by `preview/scripts/generate-schema-types.mjs`.
// Do not edit this file manually.

/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "BatchPushStatus".
 */
export type BatchPushStatus = "not-pushed" | "pushed";
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "JobKind".
 */
export type JobKind = "lesson-generate" | "new-vocab" | "sync-media";
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "JobStatus".
 */
export type JobStatus = "queued" | "running" | "succeeded" | "failed";
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "StudyLane".
 */
export type StudyLane = "lesson" | "new-vocab" | "reading-speed" | "grammar" | "listening";

export interface PreviewContract {}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "BatchPreviewResponse".
 */
export interface BatchPreviewResponse {
  batch: CardBatch;
  canonical_batch_path: string;
  preview_batch_path: string;
  synced_batch_path?: string | null;
  push_status?: ("not-pushed" | "pushed") | null;
  media_hydrated?: boolean | null;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "CardBatch".
 */
export interface CardBatch {
  schema_version?: "1";
  metadata: LessonMetadata;
  /**
   * @minItems 1
   */
  notes: GeneratedNote[];
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "LessonMetadata".
 */
export interface LessonMetadata {
  lesson_id: string;
  title: string;
  topic: string;
  lesson_date: string;
  source_description: string;
  target_deck?: string | null;
  tags?: string[];
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "GeneratedNote".
 */
export interface GeneratedNote {
  item: LessonItem;
  /**
   * @minItems 1
   */
  cards: CardPreview[];
  approved?: boolean;
  note_key?: string;
  lane?: "lesson" | "new-vocab" | "reading-speed" | "grammar" | "listening";
  skill_tags?: string[];
  duplicate_status?: "new" | "exact-duplicate" | "near-duplicate";
  duplicate_note_key?: string | null;
  duplicate_note_id?: number | null;
  duplicate_source?: string | null;
  inclusion_reason?: string;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "LessonItem".
 */
export interface LessonItem {
  id: string;
  lesson_id: string;
  item_type: "vocab" | "phrase" | "grammar" | "dialogue" | "number";
  korean: string;
  english: string;
  pronunciation?: string | null;
  examples?: ExampleSentence[];
  notes?: string | null;
  tags?: string[];
  lane?: "lesson" | "new-vocab" | "reading-speed" | "grammar" | "listening";
  skill_tags?: string[];
  source_ref?: string | null;
  image_prompt?: string | null;
  audio?: MediaAsset | null;
  image?: MediaAsset | null;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "ExampleSentence".
 */
export interface ExampleSentence {
  korean: string;
  english: string;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "MediaAsset".
 */
export interface MediaAsset {
  path: string;
  prompt?: string | null;
  source_url?: string | null;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "CardPreview".
 */
export interface CardPreview {
  id: string;
  item_id: string;
  kind:
    | "recognition"
    | "production"
    | "listening"
    | "number-context"
    | "read-aloud"
    | "chunked-reading"
    | "decodable-passage";
  front_html: string;
  back_html: string;
  audio_path?: string | null;
  image_path?: string | null;
  approved?: boolean;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "DashboardBatch".
 */
export interface DashboardBatch {
  canonical_batch_path: string;
  preview_batch_path: string;
  title: string;
  topic: string;
  lesson_date: string;
  target_deck?: string | null;
  notes: number;
  cards: number;
  approved_notes: number;
  approved_cards: number;
  audio_notes: number;
  image_notes: number;
  exact_duplicates: number;
  near_duplicates: number;
  push_status?: "not-pushed" | "pushed";
  media_hydrated?: boolean;
  synced_batch_path?: string | null;
  lanes?: ("lesson" | "new-vocab" | "reading-speed" | "grammar" | "listening")[];
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "DashboardLessonContext".
 */
export interface DashboardLessonContext {
  path: string;
  label: string;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "DashboardResponse".
 */
export interface DashboardResponse {
  status: ServiceStatus;
  stats: DashboardStats;
  recent_batches?: DashboardBatch[];
  lesson_contexts?: DashboardLessonContext[];
  syncable_files?: string[];
  defaults?: PreviewDefaults;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "ServiceStatus".
 */
export interface ServiceStatus {
  backend_ok?: boolean;
  anki_connect_ok?: boolean;
  anki_connect_version?: number | null;
  openai_configured?: boolean;
  preview_ok?: boolean;
  preview_detail?: string | null;
  tailscale_ok?: boolean;
  tailscale_detail?: string | null;
  tailscale_dns_name?: string | null;
  tailscale_key_expiry_at?: string | null;
  remote_url?: string | null;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "DashboardStats".
 */
export interface DashboardStats {
  local_batch_count?: number;
  local_note_count?: number;
  local_card_count?: number;
  pending_push_count?: number;
  audio_note_count?: number;
  image_note_count?: number;
  lane_counts?: {
    [k: string]: number;
  };
  anki_note_count?: number;
  anki_card_count?: number;
  anki_deck_counts?: {
    [k: string]: number;
  };
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "PreviewDefaults".
 */
export interface PreviewDefaults {
  lesson_generate?: LessonGenerateDefaults;
  new_vocab?: NewVocabDefaults;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "LessonGenerateDefaults".
 */
export interface LessonGenerateDefaults {
  with_audio?: boolean;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "NewVocabDefaults".
 */
export interface NewVocabDefaults {
  count?: number;
  gap_ratio?: number;
  with_audio?: boolean;
  image_quality?: "auto" | "low" | "medium" | "high";
  target_deck?: string;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "DeleteBatchResult".
 */
export interface DeleteBatchResult {
  deleted_paths?: string[];
  deleted_media_paths?: string[];
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "DuplicateNote".
 */
export interface DuplicateNote {
  item_id: string;
  korean: string;
  english: string;
  existing_note_id: number;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "JobPhase".
 */
export interface JobPhase {
  key: string;
  label: string;
  status?: "pending" | "running" | "succeeded" | "failed";
  current?: number;
  total?: number;
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "JobResponse".
 */
export interface JobResponse {
  id: string;
  kind: "lesson-generate" | "new-vocab" | "sync-media";
  status: "queued" | "running" | "succeeded" | "failed";
  created_at: string;
  updated_at: string;
  progress_current?: number;
  progress_total?: number;
  progress_label?: string | null;
  phases?: JobPhase[];
  logs?: string[];
  error?: string | null;
  output_paths?: string[];
}
/**
 * This interface was referenced by `PreviewContract`'s JSON-Schema
 * via the `definition` "PushResult".
 */
export interface PushResult {
  deck_name: string;
  approved_notes: number;
  approved_cards: number;
  duplicate_notes?: DuplicateNote[];
  dry_run: boolean;
  can_push: boolean;
  notes_added?: number;
  cards_created?: number;
  pushed_note_ids?: number[];
  sync_requested?: boolean;
  sync_completed?: boolean;
  reviewed_batch_path?: string | null;
}
