// Generated by `python -m korean_anki.schema_codegen --write preview/src/lib/schema.ts`.

// Do not edit this file manually.

export type SchemaVersion = "1";

export type ItemType = "vocab" | "phrase" | "grammar" | "dialogue" | "number";

export type CardKind = "recognition" | "production" | "listening" | "number-context" | "read-aloud" | "chunked-reading" | "decodable-passage";

export type StudyLane = "lesson" | "new-vocab" | "reading-speed" | "grammar" | "listening";

export type DuplicateStatus = "new" | "exact-duplicate" | "near-duplicate";

export type VocabAdjacencyKind = "coverage-gap" | "lesson-adjacent";

export type RawSourceKind = "image" | "text";

export type QaSeverity = "error" | "warning";

export type JobStatus = "queued" | "running" | "succeeded" | "failed";

export type JobKind = "lesson-generate" | "new-vocab" | "sync-media";

export type BatchPushStatus = "not-pushed" | "pushed";

export interface ExampleSentence {
  korean: string;
  english: string;
}

export interface MediaAsset {
  path: string;
  prompt?: string | null;
  source_url?: string | null;
}

export interface LessonMetadata {
  lesson_id: string;
  title: string;
  topic: string;
  lesson_date: string;
  source_description: string;
  target_deck?: string | null;
  tags?: string[];
}

export interface LessonItem {
  id: string;
  lesson_id: string;
  item_type: "vocab" | "phrase" | "grammar" | "dialogue" | "number";
  korean: string;
  english: string;
  pronunciation?: string | null;
  examples?: ExampleSentence[];
  notes?: string | null;
  tags?: string[];
  lane?: "lesson" | "new-vocab" | "reading-speed" | "grammar" | "listening";
  skill_tags?: string[];
  source_ref?: string | null;
  image_prompt?: string | null;
  audio?: MediaAsset | null;
  image?: MediaAsset | null;
}

export interface LessonDocument {
  schema_version?: "1";
  metadata: LessonMetadata;
  items: LessonItem[];
}

export interface CardPreview {
  id: string;
  item_id: string;
  kind: "recognition" | "production" | "listening" | "number-context" | "read-aloud" | "chunked-reading" | "decodable-passage";
  front_html: string;
  back_html: string;
  audio_path?: string | null;
  image_path?: string | null;
  approved?: boolean;
}

export interface GeneratedNote {
  item: LessonItem;
  cards: CardPreview[];
  approved?: boolean;
  note_key?: string;
  lane?: "lesson" | "new-vocab" | "reading-speed" | "grammar" | "listening";
  skill_tags?: string[];
  duplicate_status?: "new" | "exact-duplicate" | "near-duplicate";
  duplicate_note_key?: string | null;
  duplicate_note_id?: number | null;
  duplicate_source?: string | null;
  inclusion_reason?: string;
}

export interface CardBatch {
  schema_version?: "1";
  metadata: LessonMetadata;
  notes: GeneratedNote[];
}

export interface ExtractionRequest {
  lesson_id: string;
  title: string;
  topic: string;
  lesson_date: string;
  source_description: string;
  item_type_default?: "vocab" | "phrase" | "grammar" | "dialogue" | "number";
  text?: string | null;
  image_path?: string | null;
  model?: string;
  qa_model?: string;
  run_qa?: boolean;
}

export interface RawSourceAsset {
  kind: "image" | "text";
  path: string;
  description: string;
}

export interface TranscriptionEntry {
  label: string;
  korean: string;
  english: string;
  pronunciation?: string | null;
  notes?: string | null;
}

export interface TranscriptionSection {
  id: string;
  title: string;
  item_type?: "vocab" | "phrase" | "grammar" | "dialogue" | "number";
  side?: string | null;
  number_system?: string | null;
  usage_notes?: string[];
  expected_entry_count?: number | null;
  target_deck?: string | null;
  tags?: string[];
  entries: TranscriptionEntry[];
}

export interface LessonTranscription {
  schema_version?: "1";
  lesson_id: string;
  title: string;
  lesson_date: string;
  source_summary: string;
  theme: string;
  goals?: string[];
  raw_sources: RawSourceAsset[];
  expected_section_count?: number | null;
  sections: TranscriptionSection[];
  notes?: string[];
}

export interface QaIssue {
  severity: "error" | "warning";
  code: string;
  message: string;
  section_id?: string | null;
}

export interface QaReport {
  schema_version?: "1";
  lesson_id: string;
  passed: boolean;
  issues?: QaIssue[];
}

export interface DuplicateNote {
  item_id: string;
  korean: string;
  english: string;
  existing_note_id: number;
}

export interface PushRequest {
  batch: CardBatch;
  dry_run?: boolean;
  deck_name?: string | null;
  source_batch_path?: string | null;
  anki_url?: string;
  sync?: boolean;
}

export interface PushResult {
  deck_name: string;
  approved_notes: number;
  approved_cards: number;
  duplicate_notes?: DuplicateNote[];
  dry_run: boolean;
  can_push: boolean;
  notes_added?: number;
  cards_created?: number;
  pushed_note_ids?: number[];
  sync_requested?: boolean;
  sync_completed?: boolean;
  reviewed_batch_path?: string | null;
}

export interface PreviewNoteRefreshRequest {
  note: GeneratedNote;
  item: LessonItem;
}

export interface DeleteBatchRequest {
  batch_path: string;
  anki_url?: string;
}

export interface DeleteBatchResult {
  deleted_paths?: string[];
  deleted_media_paths?: string[];
}

export interface PronunciationSuggestion {
  korean: string;
  pronunciation: string;
}

export interface PronunciationBatch {
  items: PronunciationSuggestion[];
}

export interface ImageGenerationDecision {
  item_id: string;
  generate_image: boolean;
  reason: string;
}

export interface ImageGenerationPlan {
  decisions: ImageGenerationDecision[];
}

export interface NewVocabProposal {
  candidate_id: string;
  korean: string;
  english: string;
  topic_tag: string;
  example_ko: string;
  example_en: string;
  proposal_reason: string;
  image_prompt: string;
  adjacency_kind: "coverage-gap" | "lesson-adjacent";
}

export interface NewVocabProposalBatch {
  proposals: NewVocabProposal[];
}

export interface PriorNote {
  note_key: string;
  korean: string;
  english: string;
  item_type: "vocab" | "phrase" | "grammar" | "dialogue" | "number";
  lane?: "lesson" | "new-vocab" | "reading-speed" | "grammar" | "listening";
  skill_tags?: string[];
  source: string;
  existing_note_id?: number | null;
}

export interface AnkiStatsSnapshot {
  note_count?: number;
  card_count?: number;
  by_template?: Record<string, number>;
  by_tag?: Record<string, number>;
}

export interface StudyState {
  generated_notes?: PriorNote[];
  imported_notes?: PriorNote[];
  anki_stats?: AnkiStatsSnapshot;
}

export interface ServiceStatus {
  backend_ok?: boolean;
  anki_connect_ok?: boolean;
  anki_connect_version?: number | null;
  openai_configured?: boolean;
}

export interface DashboardBatch {
  path: string;
  title: string;
  topic: string;
  lesson_date: string;
  target_deck?: string | null;
  notes: number;
  cards: number;
  approved_notes: number;
  approved_cards: number;
  audio_notes: number;
  image_notes: number;
  exact_duplicates: number;
  near_duplicates: number;
  push_status?: "not-pushed" | "pushed";
  media_hydrated?: boolean;
  synced_batch_path?: string | null;
  lanes?: ("lesson" | "new-vocab" | "reading-speed" | "grammar" | "listening")[];
}

export interface DashboardLessonContext {
  path: string;
  label: string;
}

export interface DashboardStats {
  local_batch_count?: number;
  local_note_count?: number;
  local_card_count?: number;
  pending_push_count?: number;
  audio_note_count?: number;
  image_note_count?: number;
  lane_counts?: Record<string, number>;
  anki_note_count?: number;
  anki_card_count?: number;
  anki_deck_counts?: Record<string, number>;
}

export interface DashboardResponse {
  status: ServiceStatus;
  stats: DashboardStats;
  recent_batches?: DashboardBatch[];
  lesson_contexts?: DashboardLessonContext[];
  syncable_files?: string[];
}

export interface NewVocabJobRequest {
  count?: number;
  gap_ratio?: number;
  lesson_context?: string | null;
  with_audio?: boolean;
  image_quality?: "auto" | "low" | "medium" | "high";
  target_deck?: string;
  anki_url?: string;
}

export interface SyncMediaJobRequest {
  input_path: string;
  output_path?: string | null;
  sync_first?: boolean;
  media_dir?: string;
  anki_url?: string;
}

export interface JobResponse {
  id: string;
  kind: "lesson-generate" | "new-vocab" | "sync-media";
  status: "queued" | "running" | "succeeded" | "failed";
  created_at: string;
  updated_at: string;
  progress_current?: number;
  progress_total?: number;
  progress_label?: string | null;
  logs?: string[];
  error?: string | null;
  output_paths?: string[];
}
