from __future__ import annotations

DEFAULT_ANKI_URL = "http://127.0.0.1:8765"
DEFAULT_PREVIEW_HOST = "127.0.0.1"
DEFAULT_PREVIEW_PORT = 8767
DEFAULT_PREVIEW_DIST_DIR = "preview/dist"

DEFAULT_MEDIA_DIR = "data/media"

DEFAULT_EXTRACTION_ITEM_TYPE = "vocab"

DEFAULT_LLM_MODEL = "gpt-5.4"
DEFAULT_QA_MODEL = "gpt-5.4-pro"
DEFAULT_TTS_MODEL = "gpt-4o-mini-tts"
DEFAULT_IMAGE_MODEL = "gpt-image-1.5"

DEFAULT_LESSON_DECK = "Korean::Lessons"
DEFAULT_LESSON_AUDIO = True

DEFAULT_NEW_VOCAB_TITLE = "New Vocab"
DEFAULT_NEW_VOCAB_TOPIC = "New Vocab"
DEFAULT_NEW_VOCAB_TARGET_DECK = "Korean::New Vocab"
DEFAULT_NEW_VOCAB_COUNT = 20
DEFAULT_NEW_VOCAB_GAP_RATIO = 0.6
DEFAULT_NEW_VOCAB_WITH_AUDIO = True

DEFAULT_GENERATE_IMAGE_QUALITY = "auto"
DEFAULT_NEW_VOCAB_IMAGE_QUALITY = "low"

DEFAULT_READING_SPEED_TOPIC = "Reading Speed"
DEFAULT_READING_SPEED_TARGET_DECK = "Korean::Reading Speed"
DEFAULT_READING_SPEED_SOURCE_DESCRIPTION = (
    "Reading-speed batch generated from known-word bank"
)
DEFAULT_READING_SPEED_MAX_READ_ALOUD = 20
DEFAULT_READING_SPEED_MAX_CHUNKED = 10
DEFAULT_READING_SPEED_PASSAGE_WORD_COUNT = 5

DEFAULT_SYNC_MEDIA_SYNC_FIRST = True

DEFAULT_SELF_HEAL_BACKEND_LABEL = "com.albertkoy.korean-anki.backend"
DEFAULT_SELF_HEAL_WATCHDOG_LABEL = "com.albertkoy.korean-anki.watchdog"
DEFAULT_SELF_HEAL_INTERVAL_SECONDS = 60
DEFAULT_SELF_HEAL_ANKI_FAILURE_THRESHOLD = 3
DEFAULT_SELF_HEAL_ANKI_RELAUNCH_COOLDOWN_MINUTES = 15
DEFAULT_TAILSCALE_MIN_KEY_TTL_DAYS = 7
